### PR TITLE
Narrow runtime dependencies to ipython

### PR DESCRIPTION
**Pull request by rymndhng**
Reduces scope of runtime dependencies to match the upstream library. See https://github.com/3dmol/3Dmol.js/blob/master/py3Dmol/setup.py#L78-L85

This should also decrease the number of dependencies installed. The metapackage `jupyter` installs optional dependencies such as `qtconsole` that are not required to use py3dmol.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by RMeli** [comment]
Sorry @rymndhng, I completely missed this. Could you please update this branch with the latest changes?

**Comment by milot-mirdita** [comment]
@RMeli could you please consider merging this? This might help me get a currently oversized bioconda package into somewhat acceptable shape.

**Comment by RMeli** [comment]
@conda-forge-admin, please rerender

**Comment by RMeli** [comment]
@conda-forge-admin, please rerender

**Comment by RMeli** [comment]
@milot-mirdita done, thanks for the reminder.

**Pull request merged**
