### PR TITLE
Update py3Dmol to 0.9.1

### PR DESCRIPTION
**Pull request by RMeli**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by RMeli** [comment]
@conda-forge-admin, please rerender

**Comment by RMeli** [comment]
@dkoes Version 0.8.0 had the file `py3Dmol-0.8.0.tar.gz` on PyPI, while subsequent versions do not. Any chance it could be added to the latest version?

**Comment by dkoes** [comment]
What is suppose to be in this file and where should it reside? I am skeptical that I ever generated it.

**Comment by RMeli** [comment]
I _think_ the `*.tar.gz` file is the source distribution (I use [flit](https://flit.readthedocs.io/en/latest/) to [publish my packages to PyPI](https://github.com/RMeli/spyrmsd/blob/develop/.github/workflows/pypi.yml) and it seems to always generate that archive). It is the file that `coda-forge` uses in the recipe:

https://github.com/conda-forge/py3dmol-feedstock/blob/28f2a09c129f98a36791c2b8cc710610b72d16b1/recipe/meta.yaml#L9

I can [see on PyPI](https://pypi.org/project/py3Dmol/0.8.0/#files) that such file was available for version `0.8.0`, which is the last version available on `conda-forge`. For later versions, only wheels are available (and two `.egg` files for version `0.9.0`).

**Comment by dkoes** [comment]
Okay, this was easy enough - I just had to setup.py sdist.  There is now a tar.gz file for 0.9.1

**Comment by RMeli** [comment]
@conda-forge-admin, please restart ci

**Comment by RMeli** [comment]
Amazing, thanks @dkoes !

**Comment by RMeli** [comment]
Pinging @mcs07, looks like this PR is ready to go. I added myself as maintainer, I hope that's ok.

**Pull request merged**
